### ISSUE TITLE
 request.headers.merge is not work.

### ISSUE THREAD

**Issue by penguinwokrs** [lynndylanhurley/devise_token_auth#1167]
https://www.rubydoc.info/gems/devise_token_auth#Testing

reqeust does not work with minitest.
Previously it was working, devise_token_auth 0.1.42
What should I do to work?

ruby
```
ruby 2.4.3
```

gems
```
rails (5.1.6)
devise (4.4.3)
devise_token_auth (0.1.43) 
active_model_serializers (0.10.7)
```

* test code
test/controllers/notices_controller_test.rb
```
# frozen_string_literal: true

class NoticesControllerTest < ActionController::TestCase
  include ::Devise::Test::ControllerHelpers
  setup do
    @routes = Engine.routes
    @user = users(:valid_user)
    request.headers.merge!(@user.create_new_auth_token)
  end

  test 'should success get notices' do
    get :index
    assert_response :success
  end
end
```

log
```
Minitest::Assertion: Expected response to be a <2XX: success>, but was a <401: Unauthorized>
Response body: {"errors":["Please register or login."]}
test/controllers/notices_controller_test.rb:17:in `block in <class:NoticesControllerTest>'
```

**Comment by penguinwokrs** [comment]
I'm sorry.
The problem was solved.
But I do not know why it worked on previous version.

code
```
# frozen_string_literal: true

class NoticesControllerTest < ActionController::TestCase
  include ::Devise::Test::ControllerHelpers
  setup do
    @routes = Engine.routes
    @user = users(:valid_user)
    @user.skip_confirmation!
    @user.save!
    request.headers.merge!(@user.create_new_auth_token)
  end

  test 'should success get notices' do
    get :index
    assert_response :success
  end
end

**Comment by penguinwokrs** [comment]
It was caused by using `SecureRandom.uuid` for uid for fixtures.


* users.yaml

before
```
valid_user:
  user_name: "user"
  email: "user@example.com"
  uid: <%= SecureRandom.uuid %>
  provider: "email"
  encrypted_password:  <%= Devise::Encryptor.digest(User, 'abc12345') %>
  confirmed_at: <%= Time.now - 100 %>
```

after
```
valid_user:
  user_name: "user"
  email: "user@example.com"
  uid: "user@example.com"
  provider: "email"
  encrypted_password:  <%= Devise::Encryptor.digest(User, 'abc12345') %>
  confirmed_at: <%= Time.now - 100 %>
```
